sudo: required
services:
  - docker


before_install:
  - docker build -t jobsforprabu/docker-react  -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true jobsforprabu/react-test npm test -- --coverage

after_success:
  - docker build -t jobsforprabu/multi-client ./client
  - docker build -t jobsforprabu/multi-nginx ./nginx
  - docker build -t jobsforprabu/multi-server ./server
  - docker build -t jobsforprabu/multi-worker ./worker

  #login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin 
  

  #take those images and push them to docker hub
  - docker push jobsforprabu/multi-client
  - docker push jobsforprabu/multi-nginx
  - docker push jobsforprabu/multi-server
  - docker push jobsforprabu/multi-worker
